title: mstfa cmly - Game Designer
description: Personal website & résumé for mstfa cmly
url: https://mstfacmly.com
author: mstfa cmly
birthday: '1984-04-11 00:00:00 +0300'
langs: العربية , English , French 
proglangs: Python, GDScript, Unreal Blueprints, & Web languages (HTML, CSS, Markdown, Liquid)
laptop: Lenovo Thinkpad 14s (AMD)
laptopsite: https://www.lenovo.com/ca/en/laptops/thinkpad/thinkpad-t-series/ThinkPad-T14s-AMD-G1/p/22TPT144SA2
OS: Fedora
OSsite: https://getfedora.org
console: Xbox Series X
consolesite: https://www.xbox.com/en-CA/consoles/xbox-series-x
browser: Firefox
browsersite: https://firefox.com
phoneOS: Android 13
phoneOSsite: https://www.android.com/13

#contact info
email: moustafa.chamli@gmail.com
twitter: "@mstfacmly"
github:
        user: mstfacmly
        repo: https://github.com/mstfacmly
repository: mstfacmly/mstfacmly.github.io
gravatar: 053189a14b858da5286971d47897ca68
medium: https://medium.com/@mstfacmly
patreon: https://patreon.com/mstfacmly
steam: mstfacmly
discord: mstfacmly#1855
linkedin: https://www.linkedin.com/in/mstfacmly
rss: atom.xml
employer: Enzyme Testing Labs / WB Games Montreal

#remote-theme: fongandrew/hydeout
permalink: pretty #/blog/:year/:month/:day/:title
markdown: kramdown
plugins:
        - jekyll-sitemap
        - jekyll-hinduarabic
        - jekyll-github-metadata
          #        - jekyll-gallery-generator
        - hijri
collections:
  drafts:
    output: true
defaults:
  - scope:
      path: ""
      type: drafts
    values:
      comments: false
      share: false
      related: false
      sitemap: false
      noindex: true

